apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- svc.yaml
- rbac.yaml
namespace: website
images:
- name: image_repo
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: f5bbafb6b879a1deb837230b00cf7e487172515c
- name: website-landing
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: 59a677789d2ed9361db101c331fdbe003b728fac
