apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- svc.yaml
namespace: website
images:
- name: image_repo
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: c23a06052ac79c4f1ff57baee16f933bbe7af52b
- name: website-landing
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: 59a677789d2ed9361db101c331fdbe003b728fac