apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy.yaml
- ing.yaml
- svc.yaml
- rbac.yaml
namespace: website
images:
- name: image_repo
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: cc8266ba7f74dd88a16882f90f097f1be8b6ca0a
- name: website-landing
  newName: rg.fr-par.scw.cloud/nevercamprepo/nevercamp/website-landing
  newTag: 59a677789d2ed9361db101c331fdbe003b728fac
